version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/backend'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/Panama'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'security'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    reviewers:
      - 'Kevin2523'
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'

  - package-ecosystem: 'npm'
    directory: '/frontend/nextaudit-app'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/Panama'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'security'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    groups:
      angular:
        patterns:
          - '@angular/*'
